add SDL2 support

diff --git a/smt-player/ffmpeg/configure b/smt-player/ffmpeg/configure
--- a/smt-player/ffmpeg/configure
+++ b/smt-player/ffmpeg/configure
@@ -288,6 +288,7 @@ External library support:
   --disable-schannel       disable SChannel SSP, needed for TLS support on
                            Windows if openssl and gnutls are not used [autodetect]
   --disable-sdl            disable sdl [autodetect]
+  --disable-sdl2           disable sdl2 [autodetect]
   --disable-securetransport disable Secure Transport, needed for TLS support
                            on OSX if openssl and gnutls are not used [autodetect]
   --enable-x11grab         enable X11 grabbing (legacy) [no]
@@ -849,7 +850,7 @@ add_compat(){
 }
 
 check_cmd(){
-    log "$@"
+    log check_cmd "$@"
     "$@" >> $logfile 2>&1
 }
 
@@ -1510,6 +1511,7 @@ EXTERNAL_LIBRARY_LIST="
     openssl
     schannel
     sdl
+    sdl2
     securetransport
     x11grab
     xlib
@@ -1968,6 +1970,7 @@ HAVE_LIST="
     perl
     pod2man
     sdl
+    sdl2
     section_data_rel_ro
     texi2html
     threads
@@ -2777,6 +2780,7 @@ pulse_outdev_deps="libpulse"
 qtkit_indev_extralibs="-framework QTKit -framework Foundation -framework QuartzCore"
 qtkit_indev_select="qtkit"
 sdl_outdev_deps="sdl"
+sdl2_outdev_deps="sdl2"
 sndio_indev_deps="sndio_h"
 sndio_outdev_deps="sndio_h"
 v4l_indev_deps="linux_videodev_h"
@@ -2957,8 +2961,13 @@ ffmpeg_deps="avcodec avfilter avformat swresample"
 ffmpeg_select="aformat_filter anull_filter atrim_filter format_filter
                null_filter
                setpts_filter trim_filter"
+if enabled sdl2; then
+ffplay_deps="avcodec avformat swscale swresample sdl2"
+ffplay_libs='$sdl2_libs'
+else
 ffplay_deps="avcodec avformat swscale swresample sdl"
 ffplay_libs='$sdl_libs'
+fi
 ffplay_select="rdft crop_filter transpose_filter hflip_filter vflip_filter rotate_filter"
 ffprobe_deps="avcodec avformat"
 ffserver_deps="avformat fork sarestart"
@@ -5595,31 +5604,59 @@ if enabled gcrypt; then
     fi
 fi
 
-if ! disabled sdl; then
-    SDL_CONFIG="${cross_prefix}sdl-config"
-    if check_pkg_config sdl SDL_events.h SDL_PollEvent; then
-        check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) >= 0x010201" $sdl_cflags &&
-        check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) < 0x010300" $sdl_cflags &&
-        enable sdl
+#add by Tony Chen
+if ! disabled sdl2; then
+    SDL_CONFIG="${cross_prefix}sdl2-config"
+    if check_pkg_config sdl2 SDL_events.h SDL_PollEvent; then
+        check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) > 0x010300" $sdl2_cflags &&
+        check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) <= 0x020002" $sdl2_cflags &&
+        enable sdl2
     else
         if "${SDL_CONFIG}" --version > /dev/null 2>&1; then
-            sdl_cflags=$("${SDL_CONFIG}" --cflags)
-            sdl_libs=$("${SDL_CONFIG}" --libs)
+            sdl2_cflags=$("${SDL_CONFIG}" --cflags)
+            sdl2_libs=$("${SDL_CONFIG}" --libs)
             check_func_headers SDL_version.h SDL_Linked_Version $sdl_cflags $sdl_libs &&
-            check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) >= 0x010201" $sdl_cflags &&
-            check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) < 0x010300" $sdl_cflags &&
-            enable sdl
+            check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) >= 0x010201" $sdl2_cflags &&
+            check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) < 0x010300" $sdl2_cflags &&
+            enable sdl2
         elif enabled sdl ; then
             die "ERROR: SDL not found"
         else
-            disable sdl
+            disable sdl2
         fi
     fi
     if test $target_os = "mingw32"; then
-        sdl_libs="$sdl_libs -mconsole"
+        sdl2_libs="$sdl2_libs -mconsole"
     fi
 fi
-enabled sdl && add_cflags $sdl_cflags && add_extralibs $sdl_libs
+enabled sdl2 && add_cflags $sdl2_cflags && add_extralibs $sdl2_libs
+
+if ! enabled sdl2; then
+	if ! disabled sdl; then
+	    SDL_CONFIG="${cross_prefix}sdl-config"
+	    if check_pkg_config sdl SDL_events.h SDL_PollEvent; then
+	        check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) >= 0x010201" $sdl_cflags &&
+	        check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) < 0x010300" $sdl_cflags &&
+	        enable sdl
+	        if "${SDL_CONFIG}" --version > /dev/null 2>&1; then
+	            sdl_cflags=$("${SDL_CONFIG}" --cflags)
+	            sdl_libs=$("${SDL_CONFIG}" --libs)
+	            check_func_headers SDL_version.h SDL_Linked_Version $sdl_cflags $sdl_libs &&
+	            check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) >= 0x010201" $sdl_cflags &&
+	            check_cpp_condition SDL.h "(SDL_MAJOR_VERSION<<16 | SDL_MINOR_VERSION<<8 | SDL_PATCHLEVEL) < 0x010300" $sdl_cflags &&
+	            enable sdl
+	        elif enabled sdl ; then
+	            die "ERROR: SDL not found"
+	        else
+	            disable sdl
+	        fi
+	    fi
+	    if test $target_os = "mingw32"; then
+	        sdl_libs="$sdl_libs -mconsole"
+	    fi
+	fi
+	enabled sdl && add_cflags $sdl_cflags && add_extralibs $sdl_libs
+fi
 
 disabled securetransport || { check_func SecIdentityCreate "-Wl,-framework,CoreFoundation -Wl,-framework,Security" &&
     check_lib2 "Security/SecureTransport.h Security/Security.h" "SSLCreateContext SecItemImport" "-Wl,-framework,CoreFoundation -Wl,-framework,Security" &&
@@ -6181,7 +6218,11 @@ echo "new filter support        ${avfilter-no}"
 echo "network support           ${network-no}"
 echo "threading support         ${thread_type-no}"
 echo "safe bitstream reader     ${safe_bitstream_reader-no}"
+if enabled sdl2; then
+echo "SDL2 support              ${sdl2-no}"
+else
 echo "SDL support               ${sdl-no}"
+fi
 echo "opencl enabled            ${opencl-no}"
 echo "texi2html enabled         ${texi2html-no}"
 echo "perl enabled              ${perl-no}"
@@ -6227,6 +6268,12 @@ test -e Makefile || echo "include $source_path/Makefile" > Makefile
 enabled stripping || strip="echo skipping strip"
 
 config_files="$TMPH config.mak doc/config.texi"
+
+if enabled sdl2; then
+sdl_cflags_choose=$sdl2_cflags
+else
+sdl_cflags_choose=$sdl_cflags
+fi
 
 cat > config.mak <<EOF
 # Automatically generated by configure - do not modify!
@@ -6330,7 +6377,7 @@ HOSTLD_O=$HOSTLD_O
 TARGET_EXEC=$target_exec $target_exec_args
 TARGET_PATH=$target_path
 TARGET_SAMPLES=${target_samples:-\$(SAMPLES)}
-CFLAGS-ffplay=$sdl_cflags
+CFLAGS-ffplay=$sdl_cflags_choose
 ZLIB=$($ldflags_filter -lz)
 LIB_INSTALL_EXTRA_CMD=$LIB_INSTALL_EXTRA_CMD
 EXTRALIBS=$extralibs
